### ISSUE TITLE
Flow crashes when trying to use Notion plugin

### ISSUE THREAD

**Issue by Shazzik** [danielduckworth/Flow.Launcher.Plugin.NotionSearch#29]
[2023-01-12.txt](https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch/files/10404166/2023-01-12.txt

Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\anser\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 01/12/2023 17:13:59
Exception:
Notion Search Exception: 
Websites: https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch
Author: Duckworth
Version: 0.1.5
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\anser\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\main.py", line 14, in <module>
    NotionSearch()
  File "C:\Users\anser\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\flowlauncher\FlowLauncher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\anser\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\plugin\notion_search.py", line 23, in query
    token = self.settings_test(user_settings)
  File "C:\Users\anser\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\plugin\notion_search.py", line 42, in settings_test
    if token := user_settings.get("notion_token"):
AttributeError: 'NoneType' object has no attribute 'get'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\anser\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\main.py", line 14, in <module>
    NotionSearch()
  File "C:\Users\anser\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\flowlauncher\FlowLauncher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\anser\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\plugin\notion_search.py", line 23, in query
    token = self.settings_test(user_settings)
  File "C:\Users\anser\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\plugin\notion_search.py", line 42, in settings_test
    if token := user_settings.get("notion_token"):
AttributeError: 'NoneType' object has no attribute 'get'
[2023-01-12.txt](https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch/files/10404163/2023-01-12.txt)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 293
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 293
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 307
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 821
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 822
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by slmpWesley** [comment]
Same error here: "AttributeError: 'NoneType' object has no attribute 'get'"

**Comment by slmpWesley** [comment]
Any solution?
