### ISSUE TITLE
Error in Plugin

### ISSUE THREAD

**Issue by xygn** [danielduckworth/Flow.Launcher.Plugin.NotionSearch#3]
I have added the Notion Secret Key with read permission along with the page integration.

Here is the error it shows:

Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues/new
1. upload log file: C:\Users\jason\AppData\Roaming\FlowLauncher\Logs\1.9.3\2022-05-11.txt
2. copy below exception message

```
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.22616.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 05/11/2022 13:20:01
Exception:
System.IO.InvalidDataException: Notion Search|INFO:root:Integration token found.
INFO:notional.session:Initialized Notion SDK client
INFO:notional.session:Retrieving current integration bot
Traceback (most recent call last):
  File "C:\Users\jason\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\main.py", line 14, in <module>
    NotionSearch()
  File "C:\Users\jason\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\flowlauncher\FlowLauncher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\jason\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\plugin\notion_search.py", line 28, in query
    client = session_test(token)
  File "C:\Users\jason\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\plugin\helper.py", line 40, in session_test
    if client.ping() is True:
  File "C:\Users\jason\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\notional\session.py", line 486, in ping
    me = self.users.me()
  File "C:\Users\jason\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\notional\session.py", line 429, in me
    data = self().me()
AttributeError: 'UsersEndpoint' object has no attribute 'me'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by danielduckworth** [comment]
Thanks for the bug report @xygn, I'll look into it.

What permissions did to apply to the integration when creating the token? Try excluding access to read users. I'll work on a patch soon.

**Comment by Que-Lucas** [comment]
I'm facing the same situation, I realize that when search something fast, working properly, but when I put the key "n" and wait a little, show this error above.
