### ISSUE TITLE
New issue in flow launcher with notion integration 

### ISSUE THREAD

**Issue by Ajstylesp** [danielduckworth/Flow.Launcher.Plugin.NotionSearch#38]
Flow Launcher version: 1.13.0
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\Dell\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 02/11/2023 14:02:05
Exception:
Notion Search Exception: 
Websites: https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch
Author: Duckworth
Version: 0.1.5
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: INFO:root:Integration token found.
INFO:notional.session:Initialized Notion SDK client
INFO:notional.session:Retrieving current integration bot
INFO:root:API token is valid.
INFO:root:Processing results.
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\main.py", line 14, in <module>
    NotionSearch()
  File "C:\Users\Dell\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\flowlauncher\FlowLauncher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\Dell\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\plugin\notion_search.py", line 32, in query
    return results_processor(query, client)
  File "C:\Users\Dell\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\plugin\helper.py", line 71, in results_processor
    for result in data.execute():
  File "C:\Users\Dell\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\notional\query.py", line 397, in __next__
    item = Page.parse_obj(item)
  File "C:\Users\Dell\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\pydantic\main.py", line 511, in parse_obj
    return cls(**obj)
  File "C:\Users\Dell\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\pydantic\main.py", line 331, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for Page
properties -> Cold -> formula
  Unsupport sub-type: boolean (type=type_error)
properties -> Sub Seed -> formula
  Unsupport sub-type: boolean (type=type_error)

 ---> System.IO.InvalidDataException: INFO:root:Integration token found.
INFO:notional.session:Initialized Notion SDK client
INFO:notional.session:Retrieving current integration bot
INFO:root:API token is valid.
INFO:root:Processing results.
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\main.py", line 14, in <module>
    NotionSearch()
  File "C:\Users\Dell\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\flowlauncher\FlowLauncher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\Dell\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\plugin\notion_search.py", line 32, in query
    return results_processor(query, client)
  File "C:\Users\Dell\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\plugin\helper.py", line 71, in results_processor
    for result in data.execute():
  File "C:\Users\Dell\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\notional\query.py", line 397, in __next__
    item = Page.parse_obj(item)
  File "C:\Users\Dell\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\pydantic\main.py", line 511, in parse_obj
    return cls(**obj)
  File "C:\Users\Dell\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\pydantic\main.py", line 331, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for Page
properties -> Cold -> formula
  Unsupport sub-type: boolean (type=type_error)
properties -> Sub Seed -> formula
  Unsupport sub-type: boolean (type=type_error)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 821
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 822
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2023-02-11.txt](https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch/files/10712965/2023-02-11.txt)

**Comment by Ajstylesp** [comment]
how could i fix this

**Comment by Ajstylesp** [comment]
[2023-02-13.txt](https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch/files/10723645/2023-02-13.txt)
