### ISSUE TITLE
[Bugs] status properties cause crash

### ISSUE THREAD

**Issue by dan1mmm** [danielduckworth/Flow.Launcher.Plugin.NotionSearch#7]
```
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 07/07/2022 16:18:10
Exception:
System.IO.InvalidDataException: Notion Search|INFO:root:Integration token found.
INFO:notional.session:Initialized Notion SDK client
INFO:notional.session:Retrieving current integration bot
INFO:root:API token is valid.
INFO:root:Processing results.
Traceback (most recent call last):
  File "C:\Users\丹一梅\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\main.py", line 14, in <module>
    NotionSearch()
  File "C:\Users\丹一梅\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\flowlauncher\FlowLauncher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\丹一梅\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\plugin\notion_search.py", line 32, in query
    return results_processor(query, client)
  File "C:\Users\丹一梅\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\plugin\helper.py", line 71, in results_processor
    for result in data.execute():
  File "C:\Users\丹一梅\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\notional\query.py", line 397, in __next__
    item = Page.parse_obj(item)
  File "C:\Users\丹一梅\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\pydantic\main.py", line 511, in parse_obj
    return cls(**obj)
  File "C:\Users\丹一梅\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\lib\pydantic\main.py", line 331, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Page
properties -> Status
  Unsupport sub-type: status (type=type_error)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

> properties -> Status
>   Unsupport sub-type: status (type=type_error)

This is the main issue due to notion added a new property.
After remove the page that contained the property, plugin runs smooth.

**Comment by danielduckworth** [comment]
Thanks for the bug report. I'll do a bug squash update soon and try to address a few issues in a single release.

**Comment by tanurus** [comment]
I've got the same issue; thank you for fixing it!
