### ISSUE TITLE
Error when Trying to Search

### ISSUE THREAD

**Issue by chase-c55** [danielduckworth/Flow.Launcher.Plugin.NotionSearch#71]
Flow Launcher version: 1.14.1
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: C:\Python310\pythonw.exe
Node Path: 
Date: 04/27/2023 18:26:17
Exception:
Notion Search Exception: 
Websites: https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch
Author: Duckworth
Version: 0.2.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: INFO:root:Integration token found in Flow Launcher settings.
INFO:root:Testing API token.
INFO:notional.session:Initialized Notion SDK client
INFO:notional.session:Retrieving current integration bot
ERROR:root:API token is invalid.
ERROR:root:API token is invalid.

 ---> System.IO.InvalidDataException: INFO:root:Integration token found in Flow Launcher settings.
INFO:root:Testing API token.
INFO:notional.session:Initialized Notion SDK client
INFO:notional.session:Retrieving current integration bot
ERROR:root:API token is invalid.
ERROR:root:API token is invalid.

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 300
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 300
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 840
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by chase-c55** [comment]
[2023-04-27.txt](https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch/files/11348631/2023-04-27.txt)
